INSERT INTO [dbo].[UserAccount]
           ([UserName]
           ,[Password]
           ,[Salt]
           ,[UserRoleID]
           ,[FirstName]
           ,[MiddleName]
           ,[LastName]
           ,[EmailAddress]
           ,[IsActive]
           ,[UserCreated]
           ,[DateCreated]
           ,[UserModified]
           ,[DateModified])
     VALUES
           ('Admin',
           'fzyjtTarbKBuxvu3eKriYQ==',
           '82AP+PZTRfKLlKVlGayPZb/55SkXvzj6bIVZh3sr9nrFUX7zPcKh2/vUs7vD1IaVt7PrDJjHaAmHdHSjjRrNeg==',
           5,
           'STEAG Security System Admin',
           NULL,
           NULL,
           NULL,
           1,
           1,
            GETDATE(),
           1,
           GETDATE())

INSERT INTO [dbo].[UserAccount]
           ([UserName]
           ,[Password]
           ,[Salt]
           ,[UserRoleID]
           ,[FirstName]
           ,[MiddleName]
           ,[LastName]
           ,[EmailAddress]
           ,[IsActive]
           ,[UserCreated]
           ,[DateCreated]
           ,[UserModified]
           ,[DateModified])
     VALUES
           ('Guard1',
           'fzyjtTarbKBuxvu3eKriYQ==',
           '82AP+PZTRfKLlKVlGayPZb/55SkXvzj6bIVZh3sr9nrFUX7zPcKh2/vUs7vD1IaVt7PrDJjHaAmHdHSjjRrNeg==',
           6,
           NULL,
           NULL,
           NULL,
           NULL,
           1,
           1,
            GETDATE(),
           1,
           GETDATE())

INSERT INTO [dbo].[UserAccount]
           ([UserName]
           ,[Password]
           ,[Salt]
           ,[UserRoleID]
           ,[FirstName]
           ,[MiddleName]
           ,[LastName]
           ,[EmailAddress]
           ,[IsActive]
           ,[UserCreated]
           ,[DateCreated]
           ,[UserModified]
           ,[DateModified])
     VALUES
           ('Guard2',
           'fzyjtTarbKBuxvu3eKriYQ==',
           '82AP+PZTRfKLlKVlGayPZb/55SkXvzj6bIVZh3sr9nrFUX7zPcKh2/vUs7vD1IaVt7PrDJjHaAmHdHSjjRrNeg==',
           7,
           NULL,
           NULL,
           NULL,
           NULL,
           1,
           1,
            GETDATE(),
           1,
           GETDATE())
		   
INSERT INTO [dbo].[UserAccount]
           ([UserName]
           ,[Password]
           ,[Salt]
           ,[UserRoleID]
           ,[FirstName]
           ,[MiddleName]
           ,[LastName]
           ,[EmailAddress]
           ,[IsActive]
           ,[UserCreated]
           ,[DateCreated]
           ,[UserModified]
           ,[DateModified])
     VALUES
           ('Employee1',
           'fzyjtTarbKBuxvu3eKriYQ==',
           '82AP+PZTRfKLlKVlGayPZb/55SkXvzj6bIVZh3sr9nrFUX7zPcKh2/vUs7vD1IaVt7PrDJjHaAmHdHSjjRrNeg==',
           8,
           NULL,
           NULL,
           NULL,
           NULL,
           1,
           1,
            GETDATE(),
           1,
           GETDATE())
		   
INSERT INTO [dbo].[UserAccount]
           ([UserName]
           ,[Password]
           ,[Salt]
           ,[UserRoleID]
           ,[FirstName]
           ,[MiddleName]
           ,[LastName]
           ,[EmailAddress]
           ,[IsActive]
           ,[UserCreated]
           ,[DateCreated]
           ,[UserModified]
           ,[DateModified])
     VALUES
           ('Employee2',
           'fzyjtTarbKBuxvu3eKriYQ==',
           '82AP+PZTRfKLlKVlGayPZb/55SkXvzj6bIVZh3sr9nrFUX7zPcKh2/vUs7vD1IaVt7PrDJjHaAmHdHSjjRrNeg==',
           8,
           NULL,
           NULL,
           NULL,
           NULL,
           1,
           1,
            GETDATE(),
           1,
           GETDATE())
